malha1 = importdata('Tst_Malha1_kp10.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 10','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');
figure;
malha1 = importdata('Tst_Malha1_kp18.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 18','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');
figure;
malha1 = importdata('Tst_Malha1_kp10ki15.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 10 I=15','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');
figure;
malha1 = importdata('Tst_Malha1_kp18ki15.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 18 I = 15','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');
figure;
malha1 = importdata('Tst_Malha1_kp10ki17.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 10 I = 17','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');
figure;
malha1 = importdata('Tst_Malha1_kp10ki17kd1.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 10 I = 17 D = 1','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');
figure;
malha1 = importdata('Tst_Malha1_kp10ki17kd0.1.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 10 I = 17 D = 0.1','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');
figure;
malha1 = importdata('Tst_Malha1_kp10ki17kd0.4.txt');
plot(malha1(:,1),'r');
hold on;
plot(malha1(:,2),'b');
t = title('Erro da Malha 1 - P = 10 I = 17 D = 0.4','FontSize',12,'FontWeight','bold');
x = xlabel('Iterações','FontSize',12,'FontWeight','demi');
y = ylabel('Erro de Velocidade das Rodas (rad/s)','FontSize',12,'FontWeight','demi');
l = legend('Roda Direita','Roda Esquerda');
set(l,'FontSize',14,'FontWeight','demi');